
# Variables
PERIOD_1 = 100
PERIOD_2 = 3

PAYMENT_STATUS_PENDING = 'pending'


# Item types
HINDI_LANG = 'hindi'
ENGLISH_LANG = 'english'
LANGS = (
    (ENGLISH_LANG, ENGLISH_LANG),
    (HINDI_LANG, HINDI_LANG),
)

# Item types
KITCHEN_ITEM = 'kitchen'
STORE_ITEM = 'store'
ITEM_TYPES = (
    (KITCHEN_ITEM, KITCHEN_ITEM),
    (STORE_ITEM, STORE_ITEM),
)

REQUEST_STATUS_PENDING = 'pending'
REQUEST_STATUS_COMPLETED = 'completed'
REQUEST_STATUSES = (
    (REQUEST_STATUS_PENDING, REQUEST_STATUS_PENDING),
    (REQUEST_STATUS_COMPLETED, REQUEST_STATUS_COMPLETED),
)

# Order Statuses
ORDER_STATUS_PLACED = 'placed'
ORDER_STATUS_COMPLETED = 'completed'
ORDER_STATUSES = (
    (ORDER_STATUS_PLACED, ORDER_STATUS_PLACED),
    (ORDER_STATUS_COMPLETED, ORDER_STATUS_COMPLETED),
)

# Order Type
ORDER_TYPE_PURCHASE = 'purchase'
ORDER_TYPE_SALES = 'sales'
ORDER_TYPES = (
    (ORDER_TYPE_PURCHASE, ORDER_TYPE_PURCHASE),
    (ORDER_TYPE_SALES, ORDER_TYPE_SALES),
)

# Challan status
CHALLAN_PENDING = "pending"
CHALLAN_REUPLOAD_REQUESTED = "reupload requested"
CHALLAN_UPLOADED = "uploaded"
CHALLAN_REUPLOADED = "reuploaded"
CHALLAN_STATUSES = (
    (CHALLAN_PENDING, CHALLAN_PENDING),
    (CHALLAN_UPLOADED, CHALLAN_UPLOADED),
    (CHALLAN_REUPLOAD_REQUESTED, CHALLAN_REUPLOAD_REQUESTED),
    (CHALLAN_REUPLOADED, CHALLAN_REUPLOADED)
)


# Challan status
INVENTORY_DOC_PENDING = "pending"
INVENTORY_DOC_REUPLOAD_REQUESTED = "reupload requested"
INVENTORY_DOC_UPLOADED = "uploaded"
INVENTORY_DOC_REUPLOADED = "reuploaded"
INVENTORY_DOC_STATUSES = (
    (INVENTORY_DOC_PENDING, INVENTORY_DOC_PENDING),
    (INVENTORY_DOC_UPLOADED, INVENTORY_DOC_UPLOADED),
    (INVENTORY_DOC_REUPLOAD_REQUESTED, INVENTORY_DOC_REUPLOAD_REQUESTED),
    (INVENTORY_DOC_REUPLOADED, INVENTORY_DOC_REUPLOADED)
)

# Expenses
EXPENSES_LABOUR = "labour"
EXPENSES_OVERHEADS = "overheads"
EXPENSES_PACKAGING = "packaging"
EXPENSES_RENT = "rent"
EXPENSES_SALARIES = "salaries"
EXPENSES_TRANSPORTATION = 'transportation'
EXPENSES_UTILITY_BILLS = 'utility bills'
EXPENSES_STATUSES = (
    (EXPENSES_LABOUR, EXPENSES_LABOUR),
    (EXPENSES_OVERHEADS, EXPENSES_OVERHEADS),
    (EXPENSES_PACKAGING, EXPENSES_PACKAGING),
    (EXPENSES_RENT, EXPENSES_RENT),
    (EXPENSES_SALARIES, EXPENSES_SALARIES),
    (EXPENSES_TRANSPORTATION, EXPENSES_TRANSPORTATION),
    (EXPENSES_UTILITY_BILLS, EXPENSES_UTILITY_BILLS),
)
EXPENSES_STATUSES_LIST = [a[0] for a in EXPENSES_STATUSES]


# Business TEMPLATEs
BUSINESS_TEMPLATE_NONE = ""
BUSINESS_TEMPLATE_ADVANCE = "advance"
BUSINESS_TEMPLATE_BASIC= "basic"
BUSINESS_TEMPLATE_FREE = "free"
BUSINESS_TEMPLATES = (
    (BUSINESS_TEMPLATE_NONE, BUSINESS_TEMPLATE_NONE),
    (BUSINESS_TEMPLATE_FREE, BUSINESS_TEMPLATE_FREE),
    (BUSINESS_TEMPLATE_BASIC, BUSINESS_TEMPLATE_BASIC),
    (BUSINESS_TEMPLATE_ADVANCE, BUSINESS_TEMPLATE_ADVANCE),
)
BUSINESS_TEMPLATE_LIST = [a[0] for a in BUSINESS_TEMPLATES]

BUSINESS_TYPE_NONE = "none"
BUSINESS_TYPE_SUPPLIER = "supplier"
BUSINESS_TYPE_RESTAURANT = "restaurant"
BUSINESS_TYPES = (
    (BUSINESS_TYPE_NONE, BUSINESS_TYPE_NONE),
    (BUSINESS_TYPE_RESTAURANT, BUSINESS_TYPE_RESTAURANT),
    (BUSINESS_TYPE_SUPPLIER, BUSINESS_TYPE_SUPPLIER),
)
BUSINESS_TYPE_LIST = [a[0] for a in BUSINESS_TYPES]


# Role Types
ROLE_TYPE_USER = 'user'
ROLE_TYPE_ADMIN = 'admin'
ROLE_TYPES = (
    (ROLE_TYPE_USER, ROLE_TYPE_USER),
    (ROLE_TYPE_ADMIN, ROLE_TYPE_ADMIN),
)

# Invoice Statuses
CREDIT_TRANSACTION = 'credit'
DEBIT_TRANSACTION = 'debit'
TRANSACTION_TYEPS = (
    (CREDIT_TRANSACTION, CREDIT_TRANSACTION),
    (DEBIT_TRANSACTION, DEBIT_TRANSACTION),
)

IOS_CLIENT = 'ios'
ANDROID_CLIENT = 'android'
WEB_CLIENT = 'web'
CLIENT_TYPES = (
    (IOS_CLIENT, IOS_CLIENT),
    (ANDROID_CLIENT, ANDROID_CLIENT),
    (WEB_CLIENT, WEB_CLIENT),
)

# Notification types
NOTIFY_TYPE_NONE = ''
NOTIFY_TYPE_CREATE_ORDER = 'create order'
NOTIFY_TYPE_UPDATE_ORDER = 'update order'
NOTIFY_TYPE_CANCELLED_ORDER = 'cancelled order'

# SUGGESTED ORDER TIMING  (2pm to 8am)
SUGGESTED_ORDER_END_TIME = 10

# Secret types
SECRET_TTL = 1296000 #15 days

# Subscription Types
TRIAL_PLAN = 0
FREE_PLAN = 1
PAID_PLAN = 2

# Subscription billings
MONTHLY = 0
QUARTERLY = 1
HALFYEARLY = 2
ANNUALLY = 3
